### ISSUE TITLE
Exceptions when  trying to benchmark sudoku-sat solver

### ISSUE THREAD

**Issue by Rubydrag0n** [rkkautsar/reprobench#34]
I'm getting a crash when trying to run the benchmark or the analyzer after that. Installation and starting the server went fine before.

```$ reprobench bootstrap && reprobench manage local run
2019-06-05 00:02:08.061 | INFO     | reprobench.core.bootstrap.client:bootstrap_tasks:10 - Bootstrapping tasks...
2019-06-05 00:02:08.077 | INFO     | reprobench.core.bootstrap.client:bootstrap_tools:33 - Setting up tools...
2019-06-05 00:02:08.079 | INFO     | reprobench.core.bootstrap:cli:39 - Sending bootstrap event to server
Executing runs:   0%|                                                                                                                                                    | 0/32 [00:00<?, ?it/s]2019-06-05 00:02:08.440 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table16-2.txt
2019-06-05 00:02:08.444 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table25-2.txt
2019-06-05 00:02:08.447 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table49-1.txt
2019-06-05 00:02:08.452 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table9-4.txt
2019-06-05 00:02:08.457 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table36-4.txt
2019-06-05 00:02:08.467 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table36-5.txt
2019-06-05 00:02:08.483 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table16-1.txt
2019-06-05 00:02:08.491 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table16-5.txt
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/managers/local/manager.py", line 34, in spawn_worker
    worker.run()
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/core/worker.py", line 60, in run
    step.execute(context, config)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/executors/base.py", line 39, in execute
    tool(context).run(executor)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/tools/executable.py", line 41, in run
    err_path=self.get_err_path(),
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/executors/psmon.py", line 84, in run
    stats = monitor.run()
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/psmon/main.py", line 100, in run
    with Popen(*self.popenargs, preexec_fn=os.setpgrp, **self.kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rubydragon/Programming/sudokusat-example/env/bin/reprobench", line 10, in <module>
    sys.exit(cli())
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/console/decorators.py", line 37, in wrapper
    return func(server_address=server_address, *args, **kwargs)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/console/decorators.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/managers/local/__init__.py", line 21, in cli
    manager.run()
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/managers/base.py", line 34, in run
    self.wait()
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/managers/local/manager.py", line 44, in wait
    for _ in self.pool_iterator:
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
TypeError: expected str, bytes or os.PathLike object, not NoneType
2019-06-05 00:02:08.541 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table25-1.txt
2019-06-05 00:02:08.545 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table36-1.txt
2019-06-05 00:02:08.549 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table144-1.txt
2019-06-05 00:02:08.553 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table9-5.txt
2019-06-05 00:02:08.558 | INFO     | reprobench.core.worker:run:48 - Processing task: output/my_solver.MySudokuSolver/clasp/sudoku/table16-3.txt
2019-06-05 00:02:08.638 | INFO     | reprobench.managers.local.manager:exit:24 - Total time elapsed: 0.23797832299896982

```
Here the analyzer

```
$ reprobench analyze
Traceback (most recent call last):
  File "/home/rubydragon/Programming/sudokusat-example/env/bin/reprobench", line 10, in <module>
    sys.exit(cli())
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/console/decorators.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/core/analyzer.py", line 35, in cli
    analyzer.run()
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/core/analyzer.py", line 25, in run
    module.execute(context, config)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/statistics/tables/base.py", line 29, in execute
    df = cls.get_dataframe(config)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/reprobench/statistics/tables/run.py", line 51, in get_dataframe
    tool_df = pd.read_sql(sql, db, params=params)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/pandas/io/sql.py", line 380, in read_sql
    chunksize=chunksize)
  File "/home/rubydragon/Programming/sudokusat-example/env/lib/python3.7/site-packages/pandas/io/sql.py", line 1469, in read_query
    columns = [col_desc[0] for col_desc in cursor.description]
apsw.ExecutionCompleteError: Can't get description for statements that have completed execution
```

I don't know what causes this.

**Comment by rkkautsar** [comment]
Sorry for the bad error handling.

For the analyzer error, my guess is this is caused by pandas trying to extract empty result: https://github.com/rogerbinns/apsw/issues/160#issuecomment-108472685

As for the other error, my best guess is either the `path` (https://github.com/rkkautsar/sudokusat-example/blob/master/my_solver/__init__.py#L16) is not specified, or the task file is missing (may be moved or deleted?).

Can you try deleting the `output` folder first and retry it from scratch?

**Comment by Rubydrag0n** [comment]
My __init__.py looks like this:
'''
import os
import subprocess
from pathlib import Path

from reprobench.tools.executable import ExecutableTool
from reprobench.utils import download_file


DIR = os.path.dirname(__file__)


class MySudokuSolver(ExecutableTool):
    name = "My Sudoku Solver"

    # TODO: change this to your solver executable
    path = os.path.join(DIR, "Sudoku")

    @classmethod
    def setup(cls):
        super().setup()
        # # TODO: add setup as needed (compiling etc.)
        # # for example you can use subprocess to execute GNU Make:s
        # subprocess.run(["make"], cwd=DIR)
        subprocess.run(["make"])

    def get_cmdline(self):
        # TODO: change how your solver is executed against a task.
        # - `self.path` is as defined above
        # - `self.task` contains the path for the sudoku instance
        # - `self.parameters` contains the parameter for the run,
        #   in this case this is the `solver` parameter, whose value
        #   is either `riss` or `glucose`.

        solver = self.parameters.get("Sudoku")
        return [self.path, self.task, solver]

    @classmethod
    def is_ready(cls):
        """This checks if your solver is ready.
        If it returns false, the `setup()` method is executed
        """

        if not super().is_ready():
            return False

        # TODO: maybe check if your solver has already been compiled
        #       by checking the target executable?
        return Path(cls.path).is_file()
'''
My executable is my_solver/Sudoku

I'm still not quite sure how reprobench expects my output though, maybe that is part of the issue? Right now when I'm solving table9-1.txt for example I'm outputting into the same directory a file table9-1.sol with nothing but the solved sudoku inside, formatted the same way as the input sudokus. At least that's what the example my_solver.sh did with the bsp-sudoku1.txt.

I also tried just deleting the output folder and running it again, but it changed nothing.

**Comment by rkkautsar** [comment]
I think this line here:

```
solver = self.parameters.get("Sudoku")
```

is not like what you are thinking. As described in the comment, `self.parameters` is the parameter for the run, in the case of sudokusat example it is filled with the sat solvers like riss, glucose or clasp (as defined here: https://github.com/rkkautsar/sudokusat-example/blob/f5f4f05290116245c98abd6aa6d9653ec1abca55/benchmark.yml#L41-L43).

I think this is why this error is happening: `TypeError: expected str, bytes or os.PathLike object, not NoneType`. i.e. because there is no `Solver` parameter, in other word it is `None`.

**Comment by Rubydrag0n** [comment]
Thanks, that was indeed the issue. I guess I misunderstood the comments there.
